const translations = {
    EN: {
        eng: "English",
        thai: "Thai",
        chinese: "Chinese",
        japanese: "Japanese",
        korea: "Korea",
        academymenu: "Menu",
        lang_sett: "Language",
        schedule: "Schedule",
        classroom: "CLASSROOM",
        calendar: "CALENDAR",
        history: "HISTORY",
        minigame: "MINI GAME",
        myphoto: "MY PHOTO",
        dashboard: "Dashboard",
        classroom_sm: "Classroom",
        calendar_sm: "Calendar",
        history_sm: "History",
        minigame_sm: "Mini Game",
        myphoto_sm: "My Photo",
        alumni: "Alumni",
        askai: "Ask AI",
        home: "Home",
        quiz: "Quiz",
        cardflip: "Card Flip",
        guesswho: "Guess Who",
        wordle: "Wordle",
        summarize: "Summarize",
        online: "Online",
        onsite: "Onsite",
        alldata: "All",
        present: "Present",
        absent: "Absent",
        early: "Early",
        late: "Late",
        filters: "Filters",
        startdate: "Start Date",
        enddate: "End Date",
        apply: "Apply",
        reset: "Reset",
        today: "Today",
        lastmonth: "Last Month",
        lastweek: "Last Week",
        thismonth: "This Month",
        thisweek: "This Week",
        searchresults: "Search Results",
        classroomdetail: "Classroom Details",
        // settings
        profilesettings: "Profile Settings",
        profilesettingsdetail: "Update personal information and photo",
        privacysettings: "Privacy Settings",
        privacysettingsdetail: "Manage your data and privacy",
        notificationsettings: "Notification Settings",
        notificationsettingsdetail: "Customize your notification preferences",
        generalsettings: "General Settings",
        generalsettingsdetail: "Customize application behavior",
        language: "Language",
        languagedetail: "Select your preferred language",
        yearbook: "Yearbook",
        yearbookdetail: "View and manage your yearbook",
        logout: "Log Out",
        logoutdetail: "Sign out of your account",
        changepassword: "Change Password",
        selcetrange: "Select Range",
        // PROFILE PAGE
        contactinfo: "Contact Information",
        program: "Program:",
        personalinfo: "Personal Information",
        birthdate: "Birthdate:",
        biography: "Bio",
        religion: "Religion:",
        bloodtype: "Blood Type:",
        hobbies: "Hobbies:",
        favoritemusic: "Favorite Music:",
        favoritedrink: "Favorite Drink:",
        favoritemovie: "Favorite Movie:",
        lifegoal: "Life Goal:",
        lifestyle: "Lifestyle",
        company: "Company:",
        notspecified: "Not Specified",
        nobioyet: "No biography yet.",
        certificate: "Certificate:",
        foodallergy: "Food Allergies",
        // Menu
        dailyschedule: "Daily Schedule",
        courseclasses: "Course Classes",
        classhistory: "ATTENDANCE HISTORY",
        classroom: "Classroom",
        groupmembers: "Group Members",
        staffmembers: "Staff Members",
        sunday: "Sun",
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
        months: ["January", "February", "March", "April", "May", "June",
                 "July", "August", "September", "October", "November", "December"],
    },
    TH: {
        eng: "อังกฤษ",
        thai: "ภาษาไทย",
        chinese: "จีน",
        japanese: "ญี่ปุ่น",
        korea: "เกาหลี",
        academymenu: "เมนู",
        lang_sett: "การตั้งค่าภาษา",
        schedule: "ตารางเวลา",
        classroom: "ห้องเรียน",
        calendar: "ปฏิทิน",
        history: "ประวัติ",
        minigame: "มินิเกม",
        myphoto: "รูปภาพของฉัน",
        dashboard: "แดชบอร์ด",
        classroom_sm: "ห้องเรียน",
        calendar_sm: "ปฏิทิน",
        history_sm: "ประวัติ",
        minigame_sm: "มินิเกม",
        myphoto_sm: "รูปภาพของฉัน",
        alumni: "ศิษย์เก่า",
        askai: "ถาม AI",
        home: "หน้าแรก",
        quiz: "แบบทดสอบ",
        cardflip: "เกมพลิกการ์ด",
        guesswho: "ทายชื่อบุคคล",
        wordle: "เกมต่อคำ",
        summarize: "สรุป",
        online: "ออนไลน์",
        onsite: "ในสถานที่",
        alldata: "ทั้งหมด",
        present: "มาเรียน",
        absent: "ขาดเรียน",
        early: "มาก่อนเวลา",
        late: "มาสาย",
        filters: "ตัวกรอง",
        startdate: "วันที่เริ่มต้น",
        enddate: "วันที่สิ้นสุด",
        apply: "ยืนยันการใช้",
        reset: "ตั้งค่าใหม่",
        today: "วันนี้",
        lastmonth: "เดือนที่แล้ว",
        lastweek: "สัปดาห์ที่แล้ว",
        thismonth: "เดือนนี้",
        thisweek: "สัปดาห์นี้",
        searchresults: "ค้นหา",
        profilesettings: "การตั้งค่าโปรไฟล์",
        profilesettingsdetail: "อัปเดตข้อมูลส่วนตัวและรูปถ่าย",
        privacysettings: "การตั้งค่าความเป็นส่วนตัว",
        privacysettingsdetail: "จัดการข้อมูลและความเป็นส่วนตัว",
        notificationsettings: "การตั้งค่าการแจ้งเตือน",
        notificationsettingsdetail: "ปรับแต่งการตั้งค่าการแจ้งเตือน",
        generalsettings: "การตั้งค่าทั่วไป",
        generalsettingsdetail: "กำหนดลักษณะการทำงานของแอปพลิเคชัน",
        language: "ภาษา",
        languagedetail: "เลือกภาษาที่คุณต้องการ",
        yearbook: "หนังสือรุ่น",
        yearbookdetail: "ดูและจัดการหนังสือรุ่น",
        logout: "ออกจากระบบ",
        logoutdetail: "ลงชื่อออกจากบัญชี",
        changepassword: "เปลี่ยนรหัสผ่าน",
        selcetrange: "เลือกช่วงเวลา", // Added to match EN key (typo)
        selectrange: "เลือกช่วงเวลา",
        classroomdetail: "รายละเอียดห้องเรียน",
        // PROFILE PAGE
        contactinfo: "ข้อมูลการติดต่อ",
        program: "หลักสูตร:",
        personalinfo: "ข้อมูลส่วนบุคคล",
        birthdate: "วันเกิด:",
        bui: "ชีวประวัติ",
        religion: "ศาสนา:",
        bloodtype: "กรุ๊ปเลือด:",
        hobbies: "งานอดิเรก:",
        favoritemusic: "ดนตรีที่ชอบ:",
        favoritedrink: "เครื่องดื่มที่ชอบ:",
        favoritemovie: "ภาพยนตร์ที่ชอบ:",
        lifegoal: "เป้าหมายชีวิต:",
        lifestyle: "ไลฟ์สไตล์",
        company: "บริษัท:",
        notspecified: "ไม่ระบุ",
        nobioyet: "ยังไม่มีประวัติส่วนตัว",
        certificate: "ประกาศนียบัตร:",
        foodallergy: "อาหารที่แพ้",
        // Menu
        dailyschedule: "กำหนดการประจำวัน",
        courseclasses: "หลักสูตรชั้นเรียน",
        classhistory: "ประวัติการเข้าเรียน",
        classroom: "ห้องเรียน",
        sunday: "อา.",
        monday: "จ.",
        tuesday: "อ.",
        wednesday: "พ.",
        thursday: "พฤ.",
        friday: "ศ.",
        saturday: "ส.",
        months: ["มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน",
                    "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"]
    },
    CN: {
        eng: "英文",
        thai: "泰文",
        chinese: "中文",
        japanese: "日文",
        korea: "韩文",
        academymenu: "学院菜单",
        lang_sett: "语言设置",
        schedule: "日程",
        classroom: "教室",
        calendar: "日历",
        history: "历史记录",
        minigame: "迷你游戏",
        myphoto: "我的照片",
        alumni: "校友",
        askai: "提问AI",
        home: "首页",
        quiz: "测验",
        cardflip: "翻卡游戏",
        guesswho: "猜猜是谁",
        wordle: "猜单词",
        summarize: "总结",
        online: "线上",
        onsite: "线下",
        alldata: "全部",
        present: "出席",
        absent: "缺席",
        early: "早退",
        late: "迟到",
        filters: "筛选",
        startdate: "开始日期",
        enddate: "结束日期",
        apply: "应用",
        reset: "重置",
        today: "今天",
        lastmonth: "上个月",
        lastweek: "上周",
        thismonth: "本月",
        thisweek: "本周",
        searchresults: "搜索结果",
        profilesettings: "个人资料设置",
        profilesettingsdetail: "更新个人信息和照片",
        privacysettings: "隐私设置",
        privacysettingsdetail: "管理您的数据和隐私",
        notificationsettings: "通知设置",
        notificationsettingsdetail: "自定义您的通知偏好",
        generalsettings: "通用设置",
        generalsettingsdetail: "自定义应用程序行为",
        language: "语言",
        languagedetail: "选择您的首选语言",
        yearbook: "年鉴",
        yearbookdetail: "查看和管理您的年鉴",
        logout: "退出",
        logoutdetail: "退出您的账户",
        changepassword: "更改密码",
        selcetrange: "选择范围", // Added to match EN key (typo)
        selectrange: "选择范围",
        // PROFILE PAGE
        contactinfo: "联系信息",
        program: "课程/项目:",
        personalinfo: "个人信息",
        birthdate: "出生日期:",
        religion: "宗教信仰:",
        bloodtype: "血型:",
        hobbies: "爱好:",
        favoritemusic: "最喜欢的音乐:",
        favoritedrink: "最喜欢的饮品:",
        favoritemovie: "最喜欢的电影:",
        lifegoal: "人生目标:",
        lifestyle: "生活方式",
        company: "公司:",
        notspecified: "未指定",
        nobioyet: "暂无个人简介",
        // Menu
        dailyschedule: "每日日程",
        courseclasses: "课程班级",
        classhistory: "上课出勤历史",
    },
    JP: {
        eng: "英語",
        thai: "タイ語",
        chinese: "中国語",
        japanese: "日本語",
        korea: "韓国語",
        academymenu: "アカデミーメニュー",
        lang_sett: "言語設定",
        schedule: "スケジュール",
        classroom: "教室",
        calendar: "カレンダー",
        history: "履歴",
        minigame: "ミニゲーム",
        myphoto: "マイフォト",
        alumni: "卒業生",
        askai: "AIに質問",
        home: "ホーム",
        quiz: "クイズ",
        cardflip: "カードめくり",
        guesswho: "誰でしょう",
        wordle: "ワードル",
        summarize: "要約",
        online: "オンライン",
        onsite: "対面",
        alldata: "すべて",
        present: "出席",
        absent: "欠席",
        early: "早退",
        late: "遅刻",
        filters: "絞り込み",
        startdate: "開始日",
        enddate: "終了日",
        apply: "適用",
        reset: "リセット",
        today: "今日",
        lastmonth: "先月",
        lastweek: "先週",
        thismonth: "今月",
        thisweek: "今週",
        searchresults: "検索結果",
        profilesettings: "プロフィール設定",
        profilesettingsdetail: "個人情報と写真を更新",
        privacysettings: "プライバシー設定",
        privacysettingsdetail: "データとプライバシーを管理",
        notificationsettings: "通知設定",
        notificationsettingsdetail: "通知設定をカスタマイズ",
        generalsettings: "一般設定",
        generalsettingsdetail: "アプリケーションの動作をカスタマイズ",
        language: "言語",
        languagedetail: "ご希望の言語を選択",
        yearbook: "卒業アルバム",
        yearbookdetail: "卒業アルバムの閲覧と管理",
        logout: "ログアウト",
        logoutdetail: "アカウントからログアウト",
        changepassword: "パスワード変更",
        selcetrange: "範囲選択", // Added to match EN key (typo)
        selectrange: "範囲選択",
        // PROFILE PAGE
        contactinfo: "連絡先情報",
        program: "プログラム:",
        personalinfo: "個人情報",
        birthdate: "生年月日:",
        religion: "宗教:",
        bloodtype: "血液型:",
        hobbies: "趣味:",
        favoritemusic: "好きな音楽:",
        favoritedrink: "好きな飲み物:",
        favoritemovie: "好きな映画:",
        lifegoal: "人生の目標:",
        lifestyle: "ライフスタイル",
        company: "会社:",
        notspecified: "未指定",
        nobioyet: "自己紹介文はまだありません",
        // Menu
        dailyschedule: "日別スケジュール",
        courseclasses: "コース別クラス",
        classhistory: "授業出席履歴",
    },
    KR: {
        eng: "영어",
        thai: "태국어",
        chinese: "중국어",
        japanese: "일본어",
        korea: "한국어",
        academymenu: "아카데미 메뉴",
        lang_sett: "언어 설정",
        schedule: "일정",
        classroom: "강의실",
        calendar: "달력",
        history: "기록",
        minigame: "미니 게임",
        myphoto: "내 사진",
        alumni: "졸업생",
        askai: "AI에게 질문",
        home: "홈",
        quiz: "퀴즈",
        cardflip: "카드 뒤집기",
        guesswho: "누구일까요",
        wordle: "워들",
        summarize: "요약",
        online: "온라인",
        onsite: "현장",
        alldata: "전체",
        present: "출석",
        absent: "결석",
        early: "조퇴",
        late: "지각",
        filters: "필터",
        startdate: "시작일",
        enddate: "종료일",
        apply: "적용",
        reset: "재설정",
        today: "오늘",
        lastmonth: "지난달",
        lastweek: "지난주",
        thismonth: "이번 달",
        thisweek: "이번 주",
        searchresults: "검색 결과",
        profilesettings: "프로필 설정",
        profilesettingsdetail: "개인 정보 및 사진 업데이트",
        privacysettings: "개인 정보 설정",
        privacysettingsdetail: "데이터 및 개인 정보 관리",
        notificationsettings: "알림 설정",
        notificationsettingsdetail: "알림 환경 설정 사용자 지정",
        generalsettings: "일반 설정",
        generalsettingsdetail: "애플리케이션 동작 사용자 지정",
        language: "언어",
        languagedetail: "선호하는 언어 선택",
        yearbook: "앨범",
        yearbookdetail: "앨범 보기 및 관리",
        logout: "로그아웃",
        logoutdetail: "계정에서 로그아웃",
        changepassword: "비밀번호 변경",
        selcetrange: "기간 선택", // Added to match EN key (typo)
        selectrange: "기간 선택",
        // PROFILE PAGE
        contactinfo: "연락처 정보",
        program: "프로그램:",
        personalinfo: "개인 정보",
        birthdate: "생년월일:",
        religion: "종교:",
        bloodtype: "혈액형:",
        hobbies: "취미:",
        favoritemusic: "좋아하는 음악:",
        favoritedrink: "좋아하는 음료:",
        favoritemovie: "좋아하는 영화:",
        lifegoal: "인생 목표:",
        lifestyle: "라이프스타일",
        company: "회사:",
        notspecified: "미지정",
        nobioyet: "아직 자기소개가 없습니다",
        // Menu
        dailyschedule: "일일 일정",
        courseclasses: "코스 수업",
        classhistory: "수업 출석 기록",
    }
};


let currentLang = "EN";

function toggleLanguage(lang) {
    currentLang = lang;
    console.log("Language changed to: " + lang);
    localStorage.setItem('lang', lang);

    $("[data-lang]").each(function () {
        const key = $(this).attr("data-lang");
        $(this).text(translations[currentLang][key] || key);
    });
    $(".language-menu div").removeClass("lang-active");
    $(".language-menu div[store-translate='" + lang.toUpperCase() + "']").addClass("lang-active");

    // Listen for radio button change
    $('input[name="language"]').prop('checked', false); // Uncheck all
    $('input[name="language"][value="' + lang + '"]').prop('checked', true); // Check the selected
}

$(document).ready(function () {
    // your entire script here

    let lang = localStorage.getItem('lang') || 'EN'; // default English
    toggleLanguage(lang);

    $('input[name="language"]').change(function () {
        toggleLanguage(this.value);
    });
});