const translations = {
    EN: {
        eng: "English",
        thai: "Thai",
        chinese: "Chinese",
        japanese: "Japanese",
        korea: "Korea",
        academymenu: "Academy Menu",
        lang_sett: "Language Settings",
        schedule: "Schedule",
        classroom: "CLASSROOM",
        calendar: "CALENDAR",
        history: "HISTORY",
        minigame: "MINI GAME",
        myphoto: "MY PHOTO",
        alumni: "Alumni",
        askai: "Ask AI",
        home: "Home",
        quiz: "Quiz",
        cardflip: "Card Flip",
        guesswho: "Guess Who",
        wordle: "Wordle",
        summarize: "Summarize",
        online: "Online",
        onsite: "Onsite",
        alldata: "All",
        present: "Present",
        absent: "Absent",
        early: "Early",
        late: "Late",
        filters: "Filters",
        startdate: "Start Date",
        enddate: "End Date",
        apply: "Apply",
        reset: "Reset",
        today: "Today",
        lastmonth: "Last Month",
        lastweek: "Last Week",
        thismonth: "This Month",
        thisweek: "This Week",
        searchresults: "Search Results",
        // settings
        profilesettings: "Profile Settings",
        privacysettings: "Privacy Settings",
        notificationsettings: "Notification Settings",
        generalsettings: "General Settings",
        language: "Language",
        yearbook: "Yearbook",
        logout: "Log Out",
        changepassword: "Change Password",
        selcetrange: "Select Range",
    },
    TH: {
        eng: "อังกฤษ",
        thai: "ภาษาไทย",
        chinese: "จีน",
        japanese: "ญี่ปุ่น",
        korea: "เกาหลี",
        academymenu: "เมนูอะคาเดมี่",
        lang_sett: "การตั้งค่าภาษา",
        schedule: "ตารางเวลา",
        classroom: "ห้องเรียน",
        calendar: "ปฏิทิน",
        history: "ประวัติ",
        minigame: "มินิเกม",
        myphoto: "รูปภาพของฉัน",
        alumni: "หลักสูตร",
        askai: "ถาม AI",
        home: "หน้าแรก",
        quiz: "แบบทดสอบ",
        cardflip: "เกมพลิกการ์ด",
        guesswho: "ทายชื่อบุคคล",
        wordle: "เกมต่อคำ",
        summarize: "สรุป",
        online: "ออนไลน์",
        onsite: "ในสถานที่",
        alldata: "ทั้งหมด",
        present: "มาเรียน",
        absent: "ขาดเรียน",
        early: "มาก่อนเวลา",
        late: "มาสาย",
        filters: "ตัวกรอง",
        startdate: "วันที่เริ่มต้น",
        enddate: "วันที่สิ้นสุด",
        apply: "ยืนยันการใช้",
        reset: "ตั้งค่าใหม่",
        today: "วันนี้",
        lastmonth: "เดือนที่แล้ว",
        lastweek: "สัปดาห์ที่แล้ว",
        thismonth: "เดือนนี้",
        thisweek: "สัปดาห์นี้",
        searchresults: "ค้นหา",
        profilesettings: "การตั้งค่าโปรไฟล์",
        privacysettings: "การตั้งค่าความเป็นส่วนตัว",
        notificationsettings: "การตั้งค่าการแจ้งเตือน",
        generalsettings: "การตั้งค่าทั่วไป",
        language: "ภาษา",
        yearbook: "หนังสือรุ่น",
        logout: "ออกจากระบบ",
        changepassword: "เปลี่ยนรหัสผ่าน",
        selectrange: "เลือกช่วงเวลา",
    },
    CN: {
        eng: "英文",
        thai: "泰文",
        chinese: "中文",
        japanese: "日文",
        korea: "韩文",
        academymenu: "学院菜单",
        lang_sett: "语言设置",
        schedule: "日程",
        classroom: "教室",
        calendar: "日历",
        history: "历史记录",
        minigame: "迷你游戏",
        myphoto: "我的照片",
        alumni: "校友",
        askai: "提问AI",
        home: "首页",
        quiz: "测验",
        cardflip: "翻卡游戏",
        guesswho: "猜猜是谁",
        wordle: "猜单词",
        summarize: "总结",
        online: "线上",
        onsite: "线下",
        alldata: "全部",
        present: "出席",
        absent: "缺席",
        early: "早退",
        late: "迟到",
        filters: "筛选",
        startdate: "开始日期",
        enddate: "结束日期",
        apply: "应用",
        reset: "重置",
        today: "今天",
        lastmonth: "上个月",
        lastweek: "上周",
        thismonth: "本月",
        thisweek: "本周",
        searchresults: "搜索结果",
        profilesettings: "个人资料设置",
        privacysettings: "隐私设置",
        notificationsettings: "通知设置",
        generalsettings: "通用设置",
        language: "语言",
        yearbook: "年鉴",
        logout: "退出",
        changepassword: "更改密码",
        selectrange: "选择范围"
    },
    JP: {
        eng: "英語",
        thai: "タイ語",
        chinese: "中国語",
        japanese: "日本語",
        korea: "韓国語",
        academymenu: "アカデミーメニュー",
        lang_sett: "言語設定",
        schedule: "スケジュール",
        classroom: "教室",
        calendar: "カレンダー",
        history: "履歴",
        minigame: "ミニゲーム",
        myphoto: "マイフォト",
        alumni: "卒業生",
        askai: "AIに質問",
        home: "ホーム",
        quiz: "クイズ",
        cardflip: "カードめくり",
        guesswho: "誰でしょう",
        wordle: "ワードル",
        summarize: "要約",
        online: "オンライン",
        onsite: "対面",
        alldata: "すべて",
        present: "出席",
        absent: "欠席",
        early: "早退",
        late: "遅刻",
        filters: "絞り込み",
        startdate: "開始日",
        enddate: "終了日",
        apply: "適用",
        reset: "リセット",
        today: "今日",
        lastmonth: "先月",
        lastweek: "先週",
        thismonth: "今月",
        thisweek: "今週",
        searchresults: "検索結果",
        profilesettings: "プロフィール設定",
        privacysettings: "プライバシー設定",
        notificationsettings: "通知設定",
        generalsettings: "一般設定",
        language: "言語",
        yearbook: "卒業アルバム",
        logout: "ログアウト",
        changepassword: "パスワード変更",
        selectrange: "範囲選択"
    },
    KR: {
        eng: "영어",
        thai: "태국어",
        chinese: "중국어",
        japanese: "일본어",
        korea: "한국어",
        academymenu: "아카데미 메뉴",
        lang_sett: "언어 설정",
        schedule: "일정",
        classroom: "강의실",
        calendar: "달력",
        history: "기록",
        minigame: "미니 게임",
        myphoto: "내 사진",
        alumni: "졸업생",
        askai: "AI에게 질문",
        home: "홈",
        quiz: "퀴즈",
        cardflip: "카드 뒤집기",
        guesswho: "누구일까요",
        wordle: "워들",
        summarize: "요약",
        online: "온라인",
        onsite: "현장",
        alldata: "전체",
        present: "출석",
        absent: "결석",
        early: "조퇴",
        late: "지각",
        filters: "필터",
        startdate: "시작일",
        enddate: "종료일",
        apply: "적용",
        reset: "재설정",
        today: "오늘",
        lastmonth: "지난달",
        lastweek: "지난주",
        thismonth: "이번 달",
        thisweek: "이번 주",
        searchresults: "검색 결과",
        profilesettings: "프로필 설정",
        privacysettings: "개인 정보 설정",
        notificationsettings: "알림 설정",
        generalsettings: "일반 설정",
        language: "언어",
        yearbook: "앨범",
        logout: "로그아웃",
        changepassword: "비밀번호 변경",
        selectrange: "기간 선택"
    }
};


let currentLang = "EN";

function toggleLanguage(lang) {
    currentLang = lang;
    console.log("Language changed to: " + lang);
    localStorage.setItem('lang', lang);

    $("[data-lang]").each(function () {
        const key = $(this).attr("data-lang");
        $(this).text(translations[currentLang][key] || key);
    });
    $(".language-menu div").removeClass("lang-active");
    $(".language-menu div[store-translate='" + lang.toUpperCase() + "']").addClass("lang-active");

    // Listen for radio button change
    $('input[name="language"]').prop('checked', false); // Uncheck all
    $('input[name="language"][value="' + lang + '"]').prop('checked', true); // Check the selected
}

$(document).ready(function () {
    // your entire script here

    let lang = localStorage.getItem('lang') || 'EN'; // default English
    toggleLanguage(lang);

    $('input[name="language"]').change(function () {
        toggleLanguage(this.value);
    });
});