const translations = {
    en: {
        eng: "English", thai: "Thai", register: "Register", infomation: "Details",
        contact_us: "Contact Information", registration_form: "Registration Form", payment: "Payment",
        idcard: "ID Card", passport: "Passport", prefix: "Prefix",
        mr: "Mr.", mrs: "Mrs.", miss: "Miss", other: "Other",
        male: "Male", female: "Female",
        firstname_en: "First Name (EN)", lastname_en: "Last Name (EN)",
        firstname_th: "First Name (TH)", lastname_th: "Last Name (TH)",
        nickname_en: "Nickname (EN)", nickname_th: "Nickname (TH)",
        gender: "Gender", birthday: "Birthday", upload_image: "Upload Image",
        email: "Email", mobile: "Mobile Number", company: "Company", position: "Position",
        username: "Username", password: "Password",
        i_accept: "I accept", policy: "Terms and Conditions & Privacy Policy",
        password_info: "Password must be 4–20 characters, using only English letters or numbers.",
        username_info: "Username must be 8–20 characters, consisting of English letters or numbers only. (By default, your registered mobile number will be used)",
        close: "Close", accept: "Accept", already: "Already have an account?", login: "Log in",
        registered: "Successfully registered.", 
        accept_register: "Accept and register",
        copy_of_idcard: "Copy of ID card",
        copy_of_passport: "Copy of Passport",
        work_certificate: "Work certificate",
        company_certificate: "Company Certificate (for business owners)",
        support_upload: "Supports image or PDF files with a size not exceeding 20 MB only.",
        nationality: "Nationality",
        save: "Save",
        logout: "Logout",
        passport_expire: "Passport Expiry Date",
        view: "Preview",
        delete: "Remove",
        file_preview: "File Preview",
        consent_notice: "Consent Notice",
        origami_form: "Origami Form",
        consent_paragraph: "This form was created by the form owner. The information you provide will be sent directly to them. Allable is not responsible for how third-party form owners collect, use, or protect your data. Please avoid sharing any personal, sensitive, or confidential information — and never submit your password.",
        consent_footer: "For your safety, please do not include any personal or sensitive details in your responses. Thank you for your understanding and cooperation.",
        reference: "Reference Person (if any, please specify)",
        warning: "Warning",
        remove: "Remove",
        preview: "Preview",
        normal: "Normal Price",
        early: "Early Bird",
        proof_of_payment: "Attach proof of payment",
        send: "Send proof of payment",
        recommend: "Recommend",
        selected: "Selected",
        wait_payment: "Waiting to send proof of payment",
        proof_payment: "Proof of payment has been sent.",
        waiting_approve: "Waiting for payment confirmation",
        confirm_approve: "Payment confirmed",
        reject_approve: "Payment declined",
        cancel_payment: "Cancel payment",
        choose_payment_method: "Choose payment method",
        payment_method: "Payment method",
        change_payment_method: "Change payment method",
    },
    th: {
        eng: "อังกฤษ", thai: "ไทย", register: "ลงทะเบียน", infomation: "รายละเอียด",
        contact_us: "ข้อมูลการติดต่อ", registration_form: "แบบฟอร์มลงทะเบียน", payment: "การชำระเงิน",
        idcard: "รหัสประจำตัวประชาชน", passport: "พาสปอร์ต", prefix: "คำนำหน้าชื่อ",
        mr: "นาย", mrs: "นาง", miss: "นางสาว", other: "อื่นๆ",
        male: "ชาย", female: "หญิง",
        firstname_en: "ชื่อ (ภาษาอังกฤษ)", lastname_en: "นามสกุล (ภาษาอังกฤษ)",
        firstname_th: "ชื่อ (ภาษาไทย)", lastname_th: "นามสกุล (ภาษาไทย)",
        nickname_en: "ชื่อเล่น (ภาษาอังกฤษ)", nickname_th: "ชื่อเล่น (ภาษาไทย)",
        gender: "เพศ", birthday: "วันเกิด", upload_image: "อัพโหดลรูปภาพ",
        email: "อีเมล", mobile: "หมายเลขโทรศัพท์มือถือ", company: "บริษัท", position: "ตำแหน่ง",
        username: "ชื่อผู้ใช้", password: "รหัสผ่าน",
        i_accept: "ข้าพเจ้ายอมรับ", policy: "ข้อกำหนดและเงื่อนไข รวมถึงนโยบายความเป็นส่วนตัว",
        password_info: "รหัสผ่านต้องมีความยาว 4–20 ตัวอักษร และใช้ได้เฉพาะตัวอักษรภาษาอังกฤษหรือตัวเลขเท่านั้น",
        username_info: "ชื่อผู้ใช้ต้องมีความยาว 8–20 ตัวอักษร และประกอบด้วยตัวอักษรภาษาอังกฤษหรือตัวเลขเท่านั้น (ค่าเริ่มต้นคือหมายเลขโทรศัพท์มือถือที่ท่านกรอกไว้)",
        close: "ปิด", accept: "ยอมรับ", already: "มีบัญชีผู้ใช้อยู่แล้ว?", login: "เข้าสู่ระบบ",
        registered: "ลงทะเบียนสำเร็จ",
        accept_register: "ยอมรับและลงทะเบียน",
        copy_of_idcard: "สำเนาบัตรประชาชน",
        copy_of_passport: "หนังสือเดินทาง",
        work_certificate: "หนังสือรับรองการทำงาน",
        company_certificate: "หนังสือรับรองของบริษัท (สำหรับเจ้าของกิจการ)",
        support_upload: "รองรับไฟล์รูปภาพหรือ pdf ที่มีขนาดไม่เกิน 20 MB เท่านั้น",
        nationality: "สัญชาติ",
        save: "บันทึกข้อมูล",
        logout: "ออกจากระบบ",
        passport_expire: "วันหมดอายุของพาสปอร์ต",
        view: "ดูเอกสาร",
        delete: "นำออก",
        file_preview: "ตัวอย่างไฟล์",
        consent_notice: "ประกาศความยินยอมในการให้ข้อมูล",
        origami_form: "แบบฟอร์ม Origami",
        consent_paragraph: "แบบฟอร์มนี้ถูกสร้างขึ้นโดยเจ้าของแบบฟอร์ม ข้อมูลที่ท่านกรอกจะถูกส่งไปยังเจ้าของแบบฟอร์มโดยตรง Allable ไม่มีส่วนรับผิดชอบต่อวิธีการเก็บ ใช้ หรือปกป้องข้อมูลของเจ้าของแบบฟอร์มบุคคลที่สาม โปรดหลีกเลี่ยงการส่งข้อมูลส่วนบุคคล ข้อมูลที่มีความละเอียดอ่อน หรือข้อมูลลับ และ ห้ามส่งรหัสผ่านของท่านโดยเด็ดขาด",
        consent_footer: "เพื่อความปลอดภัยของท่าน โปรดอย่าระบุข้อมูลส่วนตัวหรือข้อมูลที่มีความอ่อนไหวในแบบฟอร์มนี้ ขอขอบคุณสำหรับความเข้าใจและความร่วมมือของท่าน",
        reference: "ผู้แนะนำให้มาสมัคร (ถ้ามีโปรดระบุ)",
        warning: "คำเตือน",
        remove: "นำออก",
        preview: "ดูรูปภาพ",
        normal: "ราคาปกติ",
        early: "ราคาพิเศษ",
        proof_of_payment: "หลักฐานการชำระเงิน",
        send: "ส่งหลักฐานการชำระ",
        recommend: "แนะนำ",
        selected: "เลือกแล้ว",
        wait_payment: "รอส่งหลักฐานการชำระเงิน",
        proof_payment: "ส่งหลักฐานการชำระเงินแล้ว",
        waiting_approve: "รอยืนยันการชำระเงิน",
        confirm_approve: "ยืนยันการชำระเงินแล้ว",
        reject_approve: "การชำระเงินถูกปฏิเสธ",
        cancel_payment: "ยกเลิกการชำระเงิน",
        choose_payment_method: "เลือกช่องทางการชำระเงิน",
        payment_method: "ช่องทางการชำระเงิน",
        change_payment_method: "เปลี่ยนช่องทางการชำระเงิน",
    }
};